protoc -I=./ -I=${ARTF_INSTALL_DIR}/include --cpp_out=../ QuadIP.proto
protoc -I=./ -I=${ARTF_INSTALL_DIR}/include --cpp_out=../ LeoQuad.proto
protoc -I=./ -I=${ARTF_INSTALL_DIR}/include --cpp_out=../ DualArm.proto
